### ISSUE TITLE
design inseri ecosystem

### ISSUE THREAD

**Issue by bigaru** [inseri-swiss/inseri-core-wp#203]
- each block instance has separate store slice
- data can be text or binary 
- data could be very large
- contentType check vs pre-filtering -> prefilter, but it is block developer's responsibility
- WebApi calls can be parameterized -> inseri-swiss/inseri-core-wp#215 
- File calls can be parameterized -> inseri-swiss/inseri-core-wp#216 
- JSON schema validation
- block such as python, can have arbitrary input and outputs
- design how the inputs (file, web api, block output) are initialized
- design how the mapping between `input<->block` is saved
- design the whole process
- design each block instance has user-given name
- there are two types of block, 1 can consume different types of inputs, other can only consume block inputs
- in that way, it can be scaled better 

Tasks
- [x] inseri-swiss/inseri-core-wp#200 
- [x] inseri-swiss/inseri-core-wp#223
- [x] inseri-swiss/inseri-core-wp#235
- [x] inseri-swiss/inseri-core-wp#230
