### ISSUE TITLE
Assess Persistent Identifier (PID) solutions

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-core-wp#206]
inseri is enabling researchers to publish the research output in a modern and interactive format. This research output is mainly a Publication that can be seen also as a Dataset or as a Software.   
We would like to publish at least the static website - ideally with a dataset that would allow all other researchers to upload it in order to replicate the initial content. 
The permID should be linked to a data repository that can guarantee longevity (long-term availability) and sustainability (low cost)
We are mainly interested in a combination of PID and data repository:
- well-established [FAIR](https://www.go-fair.org/fair-principles/) PID solutions (citable is very important) integrated with
- well-established data repository
- with programmatic access
- at a very low cost (ideally free)
-  that can guarantee a very good longevity
- and ideally owned by one or several research institutions, and not a commercial one.

**Tasks:**
- [x] 1. see https://github.com/inseri-swiss/inseri/wiki/Technology-evaluation#pid-technologies
- [x] 2. read https://journal.code4lib.org/articles/16774
- [x] 3. check whether DaSCH can help
- [x] 4. check whether one can integrate with Zenodo, i.e., inseri.swiss will get a DOI from Zenodo
- [x] 5. see also [Guides to Choosing Persistent Identifiers - Version 3](https://zenodo.org/record/4192174#.YyqbB-xBzSU)
