### ISSUE TITLE
Public presence for MVP 

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-core-wp#263]
- [x] Public instance inseri-swiss/inseri-core-wp#211 
- [x]  DIY (Do It Yourself): Documentation on  page inseri-swiss/inseri-core-wp#210 
- [x] Documentation inseri-swiss/inseri-core-wp#258 
- [x] Chat/Forum/Discussions like inseri-swiss/inseri-core-wp#244 
- [x] repo / issues - use directly the link - https://github.com/inseri-swiss/inseri-core-wp / https://github.com/inseri-swiss/inseri-swiss  - 
- [x] no Twitter, Medium, YouTube account at MVP
  - [x] we can announce inseri.swiss updates on our Twitter / LinkedIn / professional network
- [x] mailing list - inseri-community
- [x] in beta (as disclaimer) - Major=0 in semantic versioning
- [x] data privacy disclaimer
