### ISSUE TITLE
Improve documentation and homepage

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-core-wp#297]
- [x] add IIIF Viewer Block to documentation
- [x] add Cytoscape Block to documentation After inseri-swiss/inseri-core-wp#221
- [x] add Data Flow to documentation inseri-swiss/inseri-core-wp#221
- [x] add Copy&Paste / Duplicate documentation inseri-swiss/inseri-core-wp#221 
- [x] add info about inseri name
- [x] add docs about the hidden blocks: Text Editor, Web API, Python, Media Collection
- [x] integrate Data Flow into the tutorials
- [x] rename 1) "configuration panel" to settings sidebar, 2) side panel -> sidebar
