### ISSUE TITLE
Improve documentation and homepage 

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-core-wp#327]
- [ ] decide whether to add note about the history of the project
- [ ] add hierarchical json example to Data Flow block
- [ ] add how to transform csv to be used in Plotly or Data Flow blocks
- [ ] fix typo in https://docs.inseri.swiss/features/share_state/
