### ISSUE TITLE
Stable Release Plan

### ISSUE THREAD

**Issue by bigaru** [inseri-swiss/inseri-core-wp#329]
- [x] https://github.com/inseri-swiss/inseri-core-wp/issues/344  [must]
- [x] reduce dependencies 
    - [x] create common entry point for common dependencies such as mantine (similar to globalScript) inseri-swiss/inseri-core-wp/pull/137 [nice-to-have]
    - use webpack-bundle-analyzer
    - [x] remove axios  inseri-swiss/inseri-core-wp/pull/146
- [x] update dependencies including npm
- [x] parametrize the e2e test (WP, PHP)
- [x] documentation (see [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)) [must]
    - [x]  Code of conduct
    - [x]  CONTRIBUTING
- ~~Mantine v7 Upgrade~~
- ~~[ ] maybe change data table library?~~
- [x] inseri-swiss/inseri-core-wp#317 [nice-to-have]
- ~~export types `.d.ts`  in lighthouse entrypoint~~ [nice-to-have]
- [x] make consistent layout/design across blocks
   - [x] inseri-swiss/inseri-core-wp#341
- ~~consolidate internal block stores~~
- [x] update inseri-core description - https://github.com/inseri-swiss/inseri-core-wp/pull/363
