### ISSUE TITLE
Improve documentation and homepage Sprint 19

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri-core-wp#337]
- [x] Update https://inseri.swiss/2023/02/hello-world/ and the corresponding tutorial to use the inseri logos. UZH logo was updated https://www.cd.uzh.ch/en/elements.html#UZH_Logo 
- [x] Update Download Block docs to include https://github.com/inseri-swiss/inseri-core-wp/issues/285 
- [x] Integrate block name https://github.com/inseri-swiss/inseri-core-wp/issues/325 
- [x] Check whether any implication related to https://github.com/inseri-swiss/inseri-core-wp/issues/326 (Concept DOI?)
- [x] R Code block example and docs https://github.com/inseri-swiss/inseri-core-wp/issues/262 
- [x] integrate https://github.com/inseri-swiss/inseri-core-wp/pull/139#issuecomment-2258233243
- [x] How to r_packages docs like https://docs.inseri.swiss/how-to/python_packages/
- [x] how-to-use-plotly-with-r like https://docs.inseri.swiss/how-to/visualizations/#how-to-use-plotly-with-python
